// Generated by `zig build`; DO NOT EDIT.
const textDecoder = new TextDecoder('utf-8');

const wasmMemoryBuf = undefined;
function wasmGetMemory() {
    if (wasmMemoryBuf === undefined || wasmMemoryBuf !== wasm.memory.buffer) {
        wasmMemoryBuf = new Uint8Array(wasm.memory.buffer);
    }
    return wasmMemoryBuf;
}

function wasmGetString(ptr, len) {
    return textDecoder.decode(wasmGetMemory().slice(ptr, ptr + len));
}

/* Gen */
export function sysjs_console_log(string, string_len) {
    const l0 = wasmGetString(string, string_len);
    console.log(l0)
}
export function sysjs_console_log2(string, string_len, v1, v1_len) {
    const l0 = wasmGetString(string, string_len);
    const l1 = wasmGetString(v1, v1_len);
    console.log2(l0, l1)
}
