// Generated by `zig build`; DO NOT EDIT.
let wasm = undefined;
let wasm_memory_buf = undefined;
function wasmGetMemory() {
    if (wasm_memory_buf === undefined || wasm_memory_buf !== wasm.memory.buffer) {
        wasm_memory_buf = new Uint8Array(wasm.memory.buffer);
    }
    return wasm_memory_buf;
}

function wasmGetDataView() {
    return new DataView(wasm.memory.buffer);
}

function wasmGetSlice(ptr, len) {
    return wasmGetMemory().slice(ptr, ptr + len);
}

let wasm_objects = [];
function wasmWrapObject(obj) {
    return wasm_objects.push(obj) - 1;
}

function wasmGetObject(id) {
    return wasm_objects[id];
}

export function init(wasmObj) {
    wasm = wasmObj;
}

/* Gen */
export function sysjs_console_log(string) {
    const l0 = wasmGetObject(string);
    console.log(l0);
}
export function sysjs_console_log2(string, string_len, v1, v1_len) {
    const l0 = wasmGetSlice(string, string_len);
    const l1 = wasmGetSlice(v1, v1_len);
    console.log2(l0, l1);
}
export function sysjs_TextDecoder_new() {
    return wasmWrapObject(new TextDecoder());
}
export function sysjs_TextDecoder_decode(td, str, str_len) {
    const l0 = wasmGetObject(td);
    const l1 = wasmGetSlice(str, str_len);
    return wasmWrapObject(l0.decode(l1));
}
export function sysjs_String_new(buf, buf_len) {
    const l0 = wasmGetSlice(buf, buf_len);
    return wasmWrapObject(new String(l0));
}
export function sysjs_String_charAt(string, index) {
    const l0 = wasmGetObject(string);
    const l1 = index;
    return wasmWrapObject(l0.charAt(l1));
}
export function sysjs_navigator_gpu_requestAdapter(options) {
    const l0 = {
'powerPreference': wasmGetObject(wasmGetDataView().getUint32(options + 0, true)),
};
    navigator.gpu.requestAdapter(l0);
}
